/**
 * Turns a GPX file into `src/route.ts`.
 *
 * Hand-picked waypoints cut every bend a real road makes, which understates
 * distance and pushes riders off-route. Exporting the actual route from a
 * planner (Komoot, Strava, RideWithGPS, BRouter...) and importing it here
 * gives a course accurate enough to trust the gap on.
 *
 *   npm run import-gpx -- ~/Downloads/deventer-zwolle.gpx --name "Deventer -> Zwolle"
 *
 * GPX traces carry a point every few metres, far more than needed. Points are
 * thinned with Ramer-Douglas-Peucker, which drops only those that sit within
 * --epsilon metres of the line their neighbours already describe, so the shape
 * survives at a fraction of the size.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

import { projectOntoSegment, haversineMeters, type LatLng } from '../src/geo';

const DEFAULT_EPSILON_M = 25;
const DEFAULT_OFF_ROUTE_THRESHOLD_M = 75;

function readFlag(name: string): string | undefined {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? undefined : process.argv[index + 1];
}

function readNumberFlag(name: string, fallback: number): number {
  const raw = readFlag(name);
  if (raw === undefined) return fallback;

  const parsed = Number(raw);
  if (!Number.isFinite(parsed)) {
    console.error(`--${name} expects a number, got "${raw}"`);
    process.exit(1);
  }
  return parsed;
}

/**
 * Pull track points out of GPX. Attribute order is not fixed by the spec, so
 * lat and lon are read from each tag independently rather than positionally.
 */
function parseGpx(xml: string): LatLng[] {
  // Prefer track points; fall back to route points, then plain waypoints.
  for (const tag of ['trkpt', 'rtept', 'wpt']) {
    const points: LatLng[] = [];
    const tagPattern = new RegExp(`<${tag}\\s[^>]*>`, 'g');

    for (const [openingTag] of xml.matchAll(tagPattern)) {
      const lat = /\blat\s*=\s*"([^"]+)"/.exec(openingTag)?.[1];
      const lon = /\blon\s*=\s*"([^"]+)"/.exec(openingTag)?.[1];
      if (lat === undefined || lon === undefined) continue;

      const parsed = { lat: Number(lat), lng: Number(lon) };
      if (Number.isFinite(parsed.lat) && Number.isFinite(parsed.lng)) {
        points.push(parsed);
      }
    }

    if (points.length >= 2) {
      if (tag !== 'trkpt') {
        console.warn(`No <trkpt> found; using <${tag}> instead.`);
      }
      return points;
    }
  }

  console.error('No usable points found. Is this a GPX file with a track?');
  process.exit(1);
}

/**
 * Ramer-Douglas-Peucker: keep the point furthest from the line between the
 * ends whenever it is more than `epsilonM` away, and recurse either side.
 * Iterative rather than recursive so a dense trace cannot blow the stack.
 */
function simplify(points: readonly LatLng[], epsilonM: number): LatLng[] {
  if (points.length <= 2 || epsilonM <= 0) return [...points];

  const keep = new Array<boolean>(points.length).fill(false);
  keep[0] = true;
  keep[points.length - 1] = true;

  const stack: Array<[number, number]> = [[0, points.length - 1]];

  while (stack.length > 0) {
    const [startIndex, endIndex] = stack.pop()!;
    if (endIndex <= startIndex + 1) continue;

    let furthestIndex = -1;
    let furthestDistanceM = epsilonM;

    for (let i = startIndex + 1; i < endIndex; i += 1) {
      const { distanceM } = projectOntoSegment(
        points[i]!,
        points[startIndex]!,
        points[endIndex]!,
      );
      if (distanceM > furthestDistanceM) {
        furthestDistanceM = distanceM;
        furthestIndex = i;
      }
    }

    if (furthestIndex !== -1) {
      keep[furthestIndex] = true;
      stack.push([startIndex, furthestIndex], [furthestIndex, endIndex]);
    }
  }

  return points.filter((_, i) => keep[i]);
}

function totalLengthM(points: readonly LatLng[]): number {
  let total = 0;
  for (let i = 1; i < points.length; i += 1) {
    total += haversineMeters(points[i - 1]!, points[i]!);
  }
  return total;
}

function renderRouteModule(options: {
  points: readonly LatLng[];
  routeId: string;
  routeName: string;
  sourceFile: string;
  epsilonM: number;
  thresholdM: number;
  originalPointCount: number;
}): string {
  const coordinates = options.points
    .map((p) => `  { lat: ${p.lat.toFixed(6)}, lng: ${p.lng.toFixed(6)} },`)
    .join('\n');

  return `import { createCourse, type CourseProgress } from './course';
import type { LatLng } from './geo';

/**
 * The one hardcoded route. Both devices must run the same ROUTE_ID so their
 * positions land on the same channel and are measured against the same course.
 *
 * Generated by \`npm run import-gpx\` from ${options.sourceFile}
 * (${options.originalPointCount} track points thinned to ${options.points.length} at
 * ${options.epsilonM} m tolerance). Edit the import, not this file - re-running
 * the importer overwrites it.
 */
export const ROUTE_ID = '${options.routeId}';
export const ROUTE_NAME = '${options.routeName.replace(/'/g, "\\'")}';

export const ROUTE: readonly LatLng[] = [
${coordinates}
];

/** Distance past which a rider counts as off-route. */
export const OFF_ROUTE_THRESHOLD_M = ${options.thresholdM};

const course = createCourse(ROUTE, {
  offRouteThresholdM: OFF_ROUTE_THRESHOLD_M,
});

export const ROUTE_LENGTH_M = course.lengthM;

export type RouteProgress = CourseProgress;

/** How far along the route a position is. See \`Course.progressAt\`. */
export function progressAlongRoute(
  point: LatLng,
  previousDistanceM?: number,
): RouteProgress {
  return course.progressAt(point, previousDistanceM);
}

/** The coordinate a given distance along the route. */
export function pointAtDistance(distanceM: number): LatLng {
  return course.pointAtDistance(distanceM);
}
`;
}

const inputPath = process.argv[2];
if (inputPath === undefined || inputPath.startsWith('--')) {
  console.error(
    'Usage: npm run import-gpx -- <file.gpx> [--id ID] [--name NAME]\n' +
      '                            [--epsilon METRES] [--threshold METRES] [--out PATH]',
  );
  process.exit(1);
}

let xml: string;
try {
  xml = readFileSync(resolve(inputPath), 'utf8');
} catch {
  console.error(`Could not read ${inputPath}`);
  process.exit(1);
}

const epsilonM = readNumberFlag('epsilon', DEFAULT_EPSILON_M);
const thresholdM = readNumberFlag('threshold', DEFAULT_OFF_ROUTE_THRESHOLD_M);
const outPath = resolve(readFlag('out') ?? 'src/route.ts');

const parsed = parseGpx(xml);
const simplified = simplify(parsed, epsilonM);

const routeName =
  readFlag('name') ??
  // Fall back to the GPX's own track name, then the filename.
  /<name>([^<]+)<\/name>/.exec(xml)?.[1]?.trim() ??
  basename(inputPath).replace(/\.gpx$/i, '');

const routeId =
  readFlag('id') ??
  routeName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

writeFileSync(
  outPath,
  renderRouteModule({
    points: simplified,
    routeId,
    routeName,
    sourceFile: basename(inputPath),
    epsilonM,
    thresholdM,
    originalPointCount: parsed.length,
  }),
);

const originalLengthM = totalLengthM(parsed);
const simplifiedLengthM = totalLengthM(simplified);
const lengthLossM = originalLengthM - simplifiedLengthM;

console.log(`Imported ${basename(inputPath)} -> ${outPath}`);
console.log(`  name       ${routeName}  (id: ${routeId})`);
console.log(`  points     ${parsed.length} -> ${simplified.length} at ${epsilonM} m tolerance`);
console.log(
  `  length     ${(simplifiedLengthM / 1000).toFixed(2)} km ` +
    `(${lengthLossM >= 0 ? '-' : '+'}${Math.abs(lengthLossM).toFixed(0)} m vs the raw trace)`,
);
console.log('\nRun `npm run verify` to check the imported course.');
